name: docs

on:
  # 推送到 main 时触发
  push:
    branches: [main]
  workflow_dispatch:
# 修改 GitHub bot 权限
permissions:
  contents: write
jobs:
  docs:
    # 运行环境指定 ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          # 确定版本
          version: 8
          # 安装依赖
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile]

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Build VuePress site
        run: pnpm build

      - name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v3
        with:
          pages_threshold: major_outage

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
